# Generated by Django 4.1 on 2023-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_rents_user_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number',
        ),
        migrations.AddField(
            model_name='book',
            name='currentlyRented',
            field=models.BooleanField(default=True),
        ),
    ]
