# Generated by Django 4.1 on 2023-05-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0003_remove_book_number_book_currentlyrented'),
    ]

    operations = [
        migrations.AddField(
            model_name='rents',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testproject.book'),
        ),
        migrations.AddField(
            model_name='rents',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testproject.user'),
        ),
        migrations.AlterField(
            model_name='book',
            name='currentlyRented',
            field=models.BooleanField(default=False),
        ),
    ]
