# Generated by Django 4.1 on 2023-05-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0005_rename_rents_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='dateOfRenting',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='dateOfReturn',
            field=models.DateField(),
        ),
    ]
